"""Add rating and reminder fields

Revision ID: ae0766bfdbcd
Revises: fbaecfab1f73
Create Date: 2026-04-25 13:21:51.312002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0766bfdbcd'
down_revision = 'fbaecfab1f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avaliacao', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lembrete_enviado', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('lembrete_enviado')
        batch_op.drop_column('avaliacao')

    # ### end Alembic commands ###
