"""Add 4-stage reminder fields

Revision ID: b12156332753
Revises: ae0766bfdbcd
Create Date: 2026-04-25 18:55:24.783377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b12156332753'
down_revision = 'ae0766bfdbcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lembrete_24h_enviado', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('lembrete_2h_enviado', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('lembrete_1h_enviado', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('lembrete_30min_enviado', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.drop_column('lembrete_enviado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lembrete_enviado', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
        batch_op.drop_column('lembrete_30min_enviado')
        batch_op.drop_column('lembrete_1h_enviado')
        batch_op.drop_column('lembrete_2h_enviado')
        batch_op.drop_column('lembrete_24h_enviado')

    # ### end Alembic commands ###
