"""Adiciona a coluna de valor na tabela de posts

Revision ID: fbaecfab1f73
Revises: 180133610bf2
Create Date: 2025-08-20 14:05:31.940191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbaecfab1f73'
down_revision = '180133610bf2'
branch_labels = None
depends_on = None

def upgrade():
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor', sa.Float(), nullable=False, server_default='0.0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('valor')

    # ### end Alembic commands ###
